"""
NEW FILE — in-memory Product Intelligence Profile session store.

Backs the /session, /intake, /classify endpoints (see routes/session.py,
routes/intake.py, routes/classify.py). Those three endpoints are keyed by
session_id per the API contract (build spec §13), so something has to hold
the PIP server-side between calls — this is that something.

Deliberately in-memory, same call as CITE-07's citation_cache.py
(backend/services/citation_cache.py): "intentionally in-memory for the
hackathon/demo... a persistent database can replace it later without
changing the API contract." db/pip_repository.py (PIP-05) is the eventual
real home for this if/when someone wires up actual persistence — this file
is a drop-in-replaceable stand-in, not a competing implementation. Nothing
here touches db/ or any existing file.
"""

from typing import Optional

from backend.models.pip import ProductIntelligenceProfile
from backend.services.account_store import discard_active_cases, get_case_owner, get_saved_case, save_account_case

# session_id -> ProductIntelligenceProfile
_SESSIONS: dict[str, ProductIntelligenceProfile] = {}
_SESSION_OWNERS: dict[str, str] = {}


def create_session(user_id: str | None = None) -> ProductIntelligenceProfile:
    """Create a brand-new PIP (session_id auto-generated by the model's own
    default_factory) and store it."""
    pip = ProductIntelligenceProfile()
    if user_id:
        for old_session_id in discard_active_cases(user_id):
            _SESSIONS.pop(old_session_id, None)
            _SESSION_OWNERS.pop(old_session_id, None)
    _SESSIONS[pip.session_id] = pip
    if user_id:
        _SESSION_OWNERS[pip.session_id] = user_id
        save_account_case(user_id, pip)
    return pip


def get_session(session_id: str) -> Optional[ProductIntelligenceProfile]:
    """Return the stored PIP for a session, or None if it doesn't exist."""
    pip = _SESSIONS.get(session_id)
    if pip is not None:
        return pip
    pip = get_saved_case(session_id)
    if pip is not None:
        owner = get_case_owner(session_id)
        if owner:
            _SESSION_OWNERS[session_id] = owner
        _SESSIONS[session_id] = pip
    return pip


def save_session(pip: ProductIntelligenceProfile) -> None:
    """Persist (overwrite) the PIP for its own session_id."""
    _SESSIONS[pip.session_id] = pip
    owner = _SESSION_OWNERS.get(pip.session_id) or get_case_owner(pip.session_id)
    if owner:
        _SESSION_OWNERS[pip.session_id] = owner
        save_account_case(owner, pip)


def clear_sessions() -> None:
    """Clear all sessions. Primarily useful for tests."""
    _SESSIONS.clear()
    _SESSION_OWNERS.clear()
