"""
NEW FILE — in-memory Product Intelligence Profile session store.

Backs the /session, /intake, /classify endpoints (see routes/session.py,
routes/intake.py, routes/classify.py). Those three endpoints are keyed by
session_id per the API contract (build spec §13), so something has to hold
the PIP server-side between calls — this is that something.

Deliberately in-memory, same call as CITE-07's citation_cache.py
(backend/services/citation_cache.py): "intentionally in-memory for the
hackathon/demo... a persistent database can replace it later without
changing the API contract." db/pip_repository.py (PIP-05) is the eventual
real home for this if/when someone wires up actual persistence — this file
is a drop-in-replaceable stand-in, not a competing implementation. Nothing
here touches db/ or any existing file.
"""

from typing import Optional

from backend.models.pip import ProductIntelligenceProfile

# session_id -> ProductIntelligenceProfile
_SESSIONS: dict[str, ProductIntelligenceProfile] = {}


def create_session() -> ProductIntelligenceProfile:
    """Create a brand-new PIP (session_id auto-generated by the model's own
    default_factory) and store it."""
    pip = ProductIntelligenceProfile()
    _SESSIONS[pip.session_id] = pip
    return pip


def get_session(session_id: str) -> Optional[ProductIntelligenceProfile]:
    """Return the stored PIP for a session, or None if it doesn't exist."""
    return _SESSIONS.get(session_id)


def save_session(pip: ProductIntelligenceProfile) -> None:
    """Persist (overwrite) the PIP for its own session_id."""
    _SESSIONS[pip.session_id] = pip


def clear_sessions() -> None:
    """Clear all sessions. Primarily useful for tests."""
    _SESSIONS.clear()
